# frozen_string_literal: true

module RegisterIcons
  def self.icon_replacements
    %w[
      address-book
      anchor
      angle-down
      angle-right
      angle-up
      angles-down
      angles-left
      angles-right
      angles-up
      arrow-down
      arrow-left
      arrow-rotate-left
      arrow-rotate-right
      arrow-up
      asterisk
      at
      backward
      backward-step
      ban
      bars
      bars-staggered
      bed
      bell
      bell-slash
      bold
      book
      book-open-reader
      bookmark
      box-archive
      briefcase
      calendar-days
      caret-down
      caret-left
      caret-right
      caret-up
      certificate
      chart-bar
      chart-pie
      check
      chevron-down
      chevron-left
      chevron-right
      chevron-up
      circle
      circle-check
      circle-exclamation
      circle-half-stroke
      circle-info
      circle-minus
      circle-plus
      circle-question
      circle-xmark
      code
      comment
      compress
      copy
      crosshairs
      cube
      desktop
      discourse-bookmark-clock
      download
      ellipsis
      ellipsis-vertical
      envelope
      backward-fast
      forward-fast
      file
      file-lines
      filter
      flag
      folder
      folder-open
      forward
      forward-step
      gavel
      gear
      globe
      earth-americas
      hand-point-right
      handshake-angle
      heading
      heart
      house
      id-card
      italic
      key
      left-right
      link
      link-slash
      list
      list-check
      list-ol
      list-ul
      location-dot
      lock
      magnifying-glass
      microphone-slash
      minus
      mobile-screen-button
      paintbrush
      paper-plane
      pencil
      play
      plug
      plus
      power-off
      puzzle-piece
      question
      quote-left
      quote-right
      reply
      right-from-bracket
      right-left
      right-to-bracket
      rocket
      rotate
      share
      shield-halved
      shower
      shuffle
      signal
      spinner
      square-check
      square-envelope
      square-plus
      arrows-rotate
      table
      table-columns
      tag
      temperature-three-quarters
      thumbs-down
      thumbs-up
      thumbtack
      trash-can
      triangle-exclamation
      truck-medical
      tv
      unlock
      unlock-keyhole
      up-down
      up-right-from-square
      upload
      user
      user-pen
      user-plus
      user-secret
      user-shield
      user-xmark
      users
      wand-magic
      wrench
      xmark
    ]
  end
end
